---
title: "Public Engagement Articles Published in Chinese Social Media/中文媒体文章"
author: "Muzhi Zhou"
date: "05/04/2020"
output: 
  prettydoc::html_pretty:
    theme: hpstr
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\clearpage


### [1] 2020. Coronavirus pandemic and income inequality: Double risks faced by the poor and their policy implications /收入不平等下的新冠疫情：穷人面对的双重风险和政策面对的双重挑战|Ms Muse/ 缪斯夫人 (ID:Ms-Muses)
  2020-04-01 [Read Online](https://mp.weixin.qq.com/s?__biz=MzI5MDEwNzMwMQ==&mid=2247487200&idx=1&sn=1a8ef87e04f1e401bcec0dfdbd092ee3&chksm=ec25b42adb523d3c7d77724433639e9c0abf44e1747662628b28d9c7138ac242cd1033ba6dc5&mpshare=1&scene=1&srcid=&sharer_sharetime=1586087968319&sharer_shareid=37dd4d19089c7b4b0fa70a2136ae797c&exportkey=Ar2H7WCpIU8NGxRpm8EU8Zs%3D&pass_ticket=2wxq5Jkn88DY30kW1FbVGeMhTCQ9VwaZcGzCiET9lIBovdShsDW00AVBvmYXz1j%2B#rd)
  
### [2] 2018. Family Planning: Experiences from Other Countries/ 全面二孩三周年︱换个角度引导生育：他国经验 |The Paper/澎拜
  2018-11-01 [Read Online](https://www.thepaper.cn/newsDetail_forward_2589090)

### [3] 2018. Gender difference in the choice of college major: Its impacts on first job/男生与女生的大学专业选择，如何影响初次就业？|The Intellectual /知识分子(ID:The-Intellectual)
  2018-05-12 [Read Online](https://mp.weixin.qq.com/s?__biz=MzIyNDA2NTI4Mg==&mid=2655423410&idx=3&sn=9fdfda75cff8b5daf7594adb04217cd8&chksm=f3a689dfc4d100c987f253849ef22d50bc4b90f82fb60096982ecb8f7d1bf5cfa5d13372eb92&mpshare=1&scene=1&srcid=0405SfTcdzNf95MLGUVRWEVo&sharer_sharetime=1586088689585&sharer_shareid=37dd4d19089c7b4b0fa70a2136ae797c&exportkey=AprU8oKudqQ7Xb3M%2F0o5xMU%3D&pass_ticket=2wxq5Jkn88DY30kW1FbVGeMhTCQ9VwaZcGzCiET9lIBovdShsDW00AVBvmYXz1j%2B#rd)

### [4] 2017. Maternity Leave: Could we have both babies and jobs? / 顾此失彼的女性产假|定量群学 (ID:sociologynju)
  2017-06-19 [Read Online](https://mp.weixin.qq.com/s?__biz=MzA5MzM0MzU1NQ==&mid=2650283381&idx=1&sn=17a544e0d27d3a1a259729e3c4056fa6&exportkey=AoZkODkLs58t%2BOpTVc19GHY%3D&pass_ticket=2wxq5Jkn88DY30kW1FbVGeMhTCQ9VwaZcGzCiET9lIBovdShsDW00AVBvmYXz1j%2B)

### [5] 2017. Fertility Policy: From Restriction to Promotion? /计划与变化：从限制生育到鼓励生育|定量群学 (ID:sociologynju)
  2017-06-14 [Read Online](https://mp.weixin.qq.com/s?__biz=MzA5MzM0MzU1NQ==&mid=2650283370&idx=1&sn=3bb44cf5ffe3373b4bd94809ac8cfdad&exportkey=ArT8pc7%2F080dSDcLIcKs9lM%3D&pass_ticket=P2dzgZRi0Nm1XBCOpviat5UU0pl6l1Slxgx%2BvpfzKyASpX6ebk8p6NR%2BExsZN%2Fg%2F)


### Rotating Editor-in-charge

WeChat Social Media Public Account

**定量群学 ID:sociologynju**
《定量群学》是由一群从事定量社会学研究的师生所运营的公众号。我们来自牛津大学、斯坦福大学、南京大学、复旦大学、清华大学、中山大学、东南大学和西安交通大学等高校。

**宗旨**：为社会学研究提供最新定量学术资讯；为定量分析学者提供人文交流的角落。

**内容**：重要期刊的定量社会学文献；定量分析软件使用方法；定量研究者的人文作品。

**缪斯夫人 ID:Ms-Muses**

